# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: management board reporting
on:
  schedule:
    - cron: 30 08 * * 5

jobs:
  create_issue:
    name: Create management report task
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create management report task
        uses: imjohnbo/issue-bot@3d96848fb5e9a4a473bb81ae62b4b4866a56e93a
        with:
          assignees: "Chaps76"
          labels: "weekly sync, docs-team"
          title: "Team sync"
          body: |
            ### Tasks
            
            [] review previous report & actions
            [] draft content & finalise
            [] share prior to meeting
            [] present at meeting & record decisions/actions
                    
            ### Discussion Points
            Add things to discuss below

            - [Work this week](https://github.com/orgs/github/projects/3)
          pinned: true
          close-previous: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
