# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Quarterly Risk Review
on:
  schedule:
    - cron: 15,30,45 16 * * 4 
jobs:
  create_issue:
    name: Create team sync issue
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create team sync issue
        uses: imjohnbo/issue-bot@3d96848fb5e9a4a473bb81ae62b4b4866a56e93a
        with:
          assignees: "Chaps76"
          labels: "3-month-Risk-Review"
          title: "Review Programme Risk Register"
          body: |
            ### Tasks

            - [ ] Review existing risks
            - [ ] Check update mitigations and residual scores
            - [ ] Add new & emerging risks / close down n/a risks
            - [ ] Update actions log
                         

            - [Quarterly risks](https://github.com/orgs/github/projects/3)
          pinned: true
          close-previous: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
