name: Quarterly Risk Review
on:
  schedule:
    - cron: 15,45 14 * * 4 
jobs:
  create_issue:
    name: Create team sync issue
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create team sync issue
        uses: imjohnbo/issue-bot@3d96848fb5e9a4a473bb81ae62b4b4866a56e93a
        with:
          assignees: "@Chaps76"
          labels: "3-month-Risk-Review"
          title: "Review Programme Risk Register"
          body: |
            ### Tasks

            - [ ] Review existing risks
            - [ ] Check update mitigations and residual scores
            - [ ] Add new & emerging risks / close down n/a risks
            - [ ] Update actions log
                         

            - [Quarterly risks](https://github.com/orgs/github/projects/3)
          pinned: true
          close-previous: false
        env:
          GITHUB_TOKEN: ${{ secrets.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 }}
